WORDSIZE = 2**16
WORDMASK = WORDSIZE-1

HEADER, CAPS, CODE, DATA, STACK = range(5)

# Add status flag for non-terminating failures?
HEADERLEN = 5
H_STATUS, H_REC, H_GAS, H_MEM, H_IP = range(HEADERLEN)

STATUSLEN = 7
S_NORMAL, S_OOC, S_OOG, S_OOM, S_OOA, S_OOF, S_OOS = range(STATUSLEN)
SNAMES = "S_NORMAL, S_OOC, S_OOG, S_OOM, S_OOA, S_OOF, S_OOS".split(", ")

NUMINSTR = 15
I_CREATE, I_ALLOC, I_TRANSFERCAP, I_RECURSE, I_MEMSIZE, I_MEMWRITE, I_MEMCREATE, I_ADD, I_SUB, I_JUMP, I_JUMPIF, I_CODEREAD, I_CODELEN, I_PUSH, I_MEMPUSH = range(NUMINSTR)
INAMES = "I_CREATE, I_ALLOC, I_TRANSFERCAP, I_RECURSE, I_MEMSIZE, I_MEMWRITE, I_MEMCREATE, I_ADD, I_SUB, I_JUMP, I_JUMPIF, I_CODEREAD, I_CODELEN, I_PUSH, I_MEMPUSH".split(", ")

#On Stack
ARGLEN = {
	I_CREATE: 1,
	I_ALLOC: 2,
	I_TRANSFERCAP: 2,
	I_RECURSE: 3,
	I_MEMSIZE: 1,
	I_MEMWRITE: 3,
	I_MEMCREATE: 0,
	I_ADD: 3,
	I_SUB: 3,
	I_JUMP: 1,
	I_JUMPIF: 3,
	I_CODEREAD: 3,
	I_CODELEN: 2,
	I_PUSH: 0,
	I_MEMPUSH: 2,
}

IGASCOSTS = {
	I_CREATE: HEADERLEN,
	I_ALLOC: None,
	I_TRANSFERCAP: 6,
	I_RECURSE: 20,
	I_MEMSIZE: 1,
	I_MEMWRITE: 2,
	I_MEMCREATE: 4,
	I_ADD: 5,
	I_SUB: 5,
	I_JUMP: 2,
	I_JUMPIF: 5,
	I_CODEREAD: 8,
	I_CODELEN: 3,#TODO: mind flatten()
	I_PUSH: 2,
	I_MEMPUSH: 4,
}

# TODO: cost -= arglen
IMEMCOSTS = {
	I_CREATE : HEADERLEN,#plus some constant overhead for lists?
	I_ALLOC: None,
	I_TRANSFERCAP: None,
	I_RECURSE: 0,
	I_MEMSIZE: 0,
	I_MEMWRITE: 0,
	I_MEMCREATE: 2,
	I_ADD: 0,
	I_SUB: 0,
	I_JUMP: 0,
	I_JUMPIF: 0,
	I_CODEREAD: 0,
	I_CODELEN: 0,
	I_PUSH: 1,
	I_MEMPUSH: 0,
}
